New-Item -ItemType Directory -Force -Path .github\workflows
@"
name: Run Daily Rain Prediction

on:
  schedule:
    - cron: "30 3 * * *"   # Runs daily at 9:00 AM IST (03:30 UTC)
  workflow_dispatch:       # Manual trigger option

jobs:
  predict:
    runs-on: ubuntu-latest
    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
      TWILIO_TO: ${{ secrets.TWILIO_TO }}
      LAT: ${{ secrets.LAT }}
      LON: ${{ secrets.LON }}
      CNT: ${{ secrets.CNT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run prediction script
        run: python main.py
"@ | Out-File -Encoding utf8 .github\workflows\daily.yml
